name = "discord-bot"
main = "discord-bot-cf/main.py"
compatibility_date = "2026-07-08"
compatibility_flags = ["python_workers", "disable_python_external_sdk", "disable_python_no_global_handlers"]

[vars]
DISCORD_APPLICATION_ID = ""
DISCORD_PUBLIC_KEY = ""
DISCORD_TOKEN = ""
REDIS_URL = ""
DISCORD_WEBHOOK_URL = ""

[triggers]
crons = ["*/1 * * * *"]
